formatter: "markdown table"

sections:
  show:
    - requirements
    - providers
    - inputs
    - outputs

sort:
  enabled: true
  by: name

settings:
  type: false
  anchor: false
  escape: false
  html: true
  lockfile: false

output:
  file: README.md
  mode: inject
