# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

"""Background process observer."""
import logging
import os
import signal
import subprocess
from pathlib import Path
from sys import version_info

from ops import Object

from charms.opensearch.v0.opensearch_base_charm import OpenSearchBaseCharm
from charms.opensearch.v0.opensearch_internal_data import Scope

logger = logging.getLogger(__name__)


class AsyncOpsObserver(Object):

    def __init__(self, charm: "OpenSearchBaseCharm", operation: str) -> None:
        self.charm = charm
        self.operation = operation

        # /usr/bin/juju-exec
        pass

    def start(self) -> None:
        """Start the background process if not already running."""
        if (pid := self.charm.peers_data.get(Scope.UNIT, f"pid-observer-{self.operation}", -1)) > 0:
            # ensure the process is running, and that we have permissions to signal it
            # otherwise an OSError is raised, and we need to start a new process
            try:
                os.kill(pid, 0)
                return  # the process is running and we have permissions over it
            except OSError:
                pass

        logger.info("Starting new '%s' observer process.", self.operation)

        # We need to trick Juju into thinking that we are not running
        # in a hook context, as Juju will disallow use of juju-run.
        new_env = os.environ.copy()
        if "JUJU_CONTEXT_ID" in new_env:
            new_env.pop("JUJU_CONTEXT_ID")

        # Generate the venv path based on the existing lib path
        for loc in new_env["PYTHONPATH"].split(":"):
            path = Path(loc)
            venv_path = Path(f"{loc}/../venv/lib/python{version_info.major}.{version_info.minor}/site-packages")
            if path.stem == "lib":
                new_env["PYTHONPATH"] = f"{venv_path.resolve()}:{new_env['PYTHONPATH']}"
                break

        # Input generated by the charm
        pid = subprocess.Popen(  # noqa: S603
            [
                "/usr/bin/python3",
                "scripts/async_ops_observer.py",
                "--user f{} --password f"
                ",".join(urls),
                self._run_cmd,
                self._charm.unit.name,
                self._charm.charm_dir,
            ],
            # File shouldn't close
            stdout=open(LOG_FILE_PATH, "a"),  # noqa: SIM115
            stderr=subprocess.STDOUT,
            env=new_env,
        ).pid

