# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    inputs:
      juju-version:
        required: false
        type: string
        default: 3.1/stable

jobs:
  lint:
    name: Lint
    needs:
      - test-env
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run linters
        run: tox run -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run tests
        run: tox run -e unit

  build:
    name: Build charms
    needs:
      - lint
      - unit-test
    uses: canonical/data-platform-workflows/.github/workflows/build_charms_with_cache.yaml@v2.3.9

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        tox-environments:
          - charm-integration
          - tls-integration
          - client-integration
          - ha-integration
        runner: ["ubuntu-22.04"]
        include:
          - tox-environments: h-scaling-integration
            runner: "Ubuntu_4C_16G"
    name: ${{ matrix.tox-environments }}
    needs:
      - lint
      - unit-test
      - build
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup operator environment (passing in juju version)
        # TODO: Replace with custom image on self-hosted runner
        uses: charmed-kubernetes/actions-operator@main
        if: ${{ inputs.juju-version != 0}}
        with:
          provider: lxd
          juju-channel: ${{ inputs.juju-version }}

      - name: Setup operator environment (using default juju version 3.1/stable)
        # TODO: Replace with custom image on self-hosted runner
        uses: charmed-kubernetes/actions-operator@main
        if: ${{ inputs.juju-version == 0}}
        with:
          provider: lxd
          # Replace juju version manually if it's not been passed in. This can occur whenever this
          # workflow runs on PR or on schedule.
          juju-channel: 3.1/stable

      - name: Download packed charm(s)
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name }}
      - name: Select tests
        id: select-tests
        run: |
          echo ${{ matrix.runner }}
          if [ "${{ github.event_name }}" == "schedule" ]
          then
            echo Running unstable and stable tests
            echo "mark_expression=" >> $GITHUB_OUTPUT
          else
            echo Skipping unstable tests
            echo "mark_expression=not unstable" >> $GITHUB_OUTPUT
          fi

      - name: Run integration tests
        run: |
          # set up environment - get juju version and set kernel params
          source ./setup.sh
          tox run -e ${{ matrix.tox-environments }} -- -m '${{ steps.select-tests.outputs.mark_expression }}'
        env:
          CI_PACKED_CHARMS: ${{ needs.build.outputs.charms }}
