# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:

jobs:
  build:
    name: Build charm
    strategy:
      fail-fast: false
      matrix:
        path:
        - .
        - ./tests/integration/relations/opensearch_provider/application-charm/
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@get-opensearch-systemd-logs
    with:
      path-to-charm-directory: ${{ matrix.path }}
      cache: true

  integration-test:
    name: Integration test charm | 3.5.3
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/integration_test_charm.yaml@get-opensearch-systemd-logs
    with:
      artifact-prefix: packed-charm-cache-true
      cloud: lxd
      juju-agent-version: 3.5.3
      _beta_allure_report: true
    secrets:
      # GitHub appears to redact each line of a multi-line secret
      # Avoid putting `{` or `}` on a line by itself so that it doesn't get redacted in logs
      integration-test: |
        { "AWS_ACCESS_KEY": "${{ secrets.AWS_ACCESS_KEY }}",
          "AWS_SECRET_KEY": "${{ secrets.AWS_SECRET_KEY }}",
          "GCP_ACCESS_KEY": "${{ secrets.GCP_ACCESS_KEY }}",
          "GCP_SECRET_KEY": "${{ secrets.GCP_SECRET_KEY }}",
          "GCP_SERVICE_ACCOUNT": "${{ secrets.GCP_SERVICE_ACCOUNT }}", }
    permissions:
      contents: write
