name: Tests
on:
  workflow_call:
  pull_request:

jobs:
  lint:
    name: Lint & Unit Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint
      - name: Run tests
        run: tox -e unit

  integration-test-lxd-tls:
    name: Integration tests for TLS (lxd)
    needs:
      - lint
      - unit-test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
      - name: Run integration tests
        run: |
          # set sysctl values in case the cloudinit-userdata not applied
          sudo sysctl -w vm.max_map_count=262144
          sudo sysctl -w vm.swappiness=0
          sudo sysctl -w net.ipv4.tcp_retries2=5

          tox -e tls-integration

  # integration-test-lxd-ha:
  #   name: Integration tests for HA (lxd)
  #   needs:
  #     - lint-and-unit-test
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup operator environment
  #       uses: charmed-kubernetes/actions-operator@main
  #       with:
  #         provider: lxd
  #     - name: Run integration tests
  #       run: |
  #         # set sysctl values in case the cloudinit-userdata not applied
  #         sudo sysctl -w vm.max_map_count=262144
  #         sudo sysctl -w vm.swappiness=0
  #         sudo sysctl -w net.ipv4.tcp_retries2=5
  #         tox -e ha-integration

  integration-test-client-relation:
    name: Integration tests for client relation
    runs-on: ubuntu-22.04
    # Commented out while this is still in dev.
    # needs:
    #   - lint
    #   - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
      - name: Run integration tests
        run: |
          # set sysctl values in case the cloudinit-userdata not applied
          sudo sysctl -w vm.max_map_count=262144
          sudo sysctl -w vm.swappiness=0
          sudo sysctl -w net.ipv4.tcp_retries2=5

          tox -e client-integration

