# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    inputs:
      juju-version:
        required: false
        type: number
        default: 3

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run linters
        run: tox run -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run tests
        run: tox run -e unit

  build:
    name: Build charms
    needs:
      - lint
      - unit-test
    uses: canonical/data-platform-workflows/.github/workflows/build_charms_with_cache.yaml@v2.3.9

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        tox-environments:
          - charm-integration
          - tls-integration
          - client-integration
          - ha-integration
        runner: ["ubuntu-22.04"]
        include:
          - tox-environments: h-scaling-integration
            runner: "Ubuntu_4C_16G"
    name: ${{ matrix.tox-environments }}
    needs:
      - lint
      - unit-test
      - build
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Juju 3 operator environment
        # Runs on juju 3 by default
        # TODO: Replace with custom image on self-hosted runner
        uses: charmed-kubernetes/actions-operator@main
        if: ${{ inputs.juju-version == 3 || inputs.juju-version == 0}}
        with:
          provider: lxd
          juju-channel: 3.1/stable

      - name: Setup Juju 2 operator environment
        # TODO: Replace with custom image on self-hosted runner
        uses: charmed-kubernetes/actions-operator@main
        if: ${{ inputs.juju-version == 2}}
        with:
          provider: lxd
          juju-channel: 2.9/stable

      - name: Download packed charm(s)
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name }}
      - name: Select tests
        id: select-tests
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]
          then
            echo Running unstable and stable tests
            echo "mark_expression=" >> $GITHUB_OUTPUT
          else
            echo Skipping unstable tests
            echo "mark_expression=not unstable" >> $GITHUB_OUTPUT
          fi

      - name: Run integration tests
        run: |
          # Set kernel params
          sudo sysctl -w vm.max_map_count=262144 vm.swappiness=0 net.ipv4.tcp_retries2=5
          echo "${{inputs.juju-version}}"
          if [ "${{inputs.juju-version}}" != "" ]
          then
            tox run -e j${{inputs.juju-version}}-${{ matrix.tox-environments }} -- -m '${{ steps.select-tests.outputs.mark_expression }}'
          else
            # default juju version is 3
            tox run -e j3-${{ matrix.tox-environments }} -- -m '${{ steps.select-tests.outputs.mark_expression }}'
          fi
        env:
          CI_PACKED_CHARMS: ${{ needs.build.outputs.charms }}
