# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_charm.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        path:
          - .
          - tests/integration/relations/opensearch_provider/application-charm
    name: Build charm | ${{ matrix.path }}
    uses: phvalguima/data-platform-workflows/.github/workflows/build_charm.yaml@add-systemd-logs
    with:
      cache: false
      path-to-charm-directory: ${{ matrix.path }}

  integration-test:
    name: Integration test charm
    needs:
      - lint
      - unit-test
      - build
    uses: phvalguima/data-platform-workflows/.github/workflows/integration_test_charm.yaml@add-systemd-logs
    with:
      juju-agent-version: 3.6.1 # renovate: juju-agent-pin-minor
      _beta_allure_report: true
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      cloud: lxd
    permissions:
      contents: write
