# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: CI

on:
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    inputs:
      juju-snap-channel:
        description: Snap channel for Juju CLI
        default: 3.1/stable
        type: string
      libjuju-version-specifier:
        default: "==3.1.0.1"
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run linters
        run: tox run -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run tests
        run: tox run -e unit

  lib-check:
    name: Check libraries
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.1.1
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}" # FIXME: current token will expire in 2023-07-04
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  build:
    name: Build charms
    needs:
      - lib-check
      - lint
      - unit-test
    uses: canonical/data-platform-workflows/.github/workflows/build_charms_with_cache.yaml@v2.3.9

  integration:
    needs:
      - lint
      - unit-test
      - build
    strategy:
      matrix:
        version:
          - snap: 3.1/stable
          - snap: 2.9/stable
            libjuju: "==2.9.42.1"
    uses: ./.github/workflows/integration.yaml
    with:
      juju-snap-channel: ${{ inputs.juju-snap-channel }}
      libjuju-version-specifier: ${{ inputs.libjuju-version-specifier }}
      artifact-name: ${{ needs.build.outputs.artifact-name }}


