# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
on:
  workflow_call:
    inputs:
      juju-snap-channel:
        description: Snap channel for Juju CLI
        default: 3.1/stable
        type: string
      libjuju-version-specifier:
        description: |
            python-libjuju version specifier (e.g. ">=1.3")
            https://packaging.python.org/en/latest/glossary/#term-Version-Specifier
        required: false
        type: string
#    secrets:
#      integration-test:
#        description: |
#          Secrets needed in integration tests
#
#          Passed to tests with `SECRETS_FROM_GITHUB` environment variable
#
#          Use a string representation of a Python dict[str, str] built from multiple GitHub secrets
#          Do NOT put the string into a single GitHub secret—build the string from multiple GitHub secrets so that GitHub is more likely to redact the secrets in GitHub Actions logs.
#
#          Python code to verify the string format:
#          ```
#          import ast
#          secrets = ast.literal_eval("")
#          assert isinstance(secrets, dict)
#          for key, value in secrets.items():
#              assert isinstance(key, str) and isinstance(value, str)
#          ```
#        required: false

jobs:
  build:
    name: Build charms
    uses: canonical/data-platform-workflows/.github/workflows/build_charms_with_cache.yaml@v7.0.0
    with:
      charmcraft-snap-revision: 1349  # version 2.3.0
    permissions:
      actions: write

  integration-test:
    name: Integration test charm | ${{ matrix.juju.agent }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        juju:
          - agent: 3.1.7
            libjuju: 3.2.3.0
    uses: canonical/data-platform-workflows/.github/workflows/integration_test_charm.yaml@main
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      cloud: lxd
      juju-agent-version: ${{ matrix.juju.agent }}
      libjuju-version-constraint: ${{ matrix.juju.libjuju }}