# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
on:
  workflow_call:
    inputs:
      juju-snap-channel:
        description: Snap channel for Juju CLI
        default: 3.1/stable
        type: string
      libjuju-version-specifier:
        description: |
            python-libjuju version specifier (e.g. ">=1.3")
            https://packaging.python.org/en/latest/glossary/#term-Version-Specifier
        required: false
        type: string

jobs:
  build:
    name: Build charms
    uses: canonical/data-platform-workflows/.github/workflows/build_charms_with_cache.yaml@v7.0.0
    permissions:
      actions: write

  integration-test:
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/integration_test_charm_self_hosted.yaml@v7.0.0
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      cloud: lxd
      juju-snap-channel: ${{ inputs.juju-snap-channel }}
      libjuju-version-constraint: ${{ inputs.juju-snap-channel }}
#    secrets:
#      integration-test: |
#        {
#          "AWS_ACCESS_KEY": "${{ secrets.AWS_ACCESS_KEY }}",
#          "AWS_SECRET_KEY": "${{ secrets.AWS_SECRET_KEY }}",
#          "GCP_ACCESS_KEY": "${{ secrets.GCP_ACCESS_KEY }}",
#          "GCP_SECRET_KEY": "${{ secrets.GCP_SECRET_KEY }}",
#        }
