# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: PR CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  # pre-integration-checks:
  #   uses: ./.github/workflows/pre_integration_checks.yaml

  # build:
  #   name: Build charms
  #   needs:
  #     - pre-integration-checks
  #   uses: canonical/data-platform-workflows/.github/workflows/build_charms_with_cache.yaml@v2.3.9

  integration:
    # needs:
    #   - pre-integration-checks
    #   - build
    strategy:
      matrix:
        include:
          - snap: 3.1/stable
            libjuju: ==3.1.0.1
          - snap: 2.9/stable
            libjuju: ==2.9.42.1
    uses: ./.github/workflows/integration.yaml
    with:
      juju-snap-channel: ${{ matrix.snap }}
      libjuju-version-specifier: ${{ matrix.libjuju }}
      artifact-name: "test"
      # ${{ needs.build.outputs.artifact-name }}
