name: Basic CI workflow caller

on:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  pull_request:

jobs:
  ci-tests:
    strategy:
      matrix:
        version:
          - snap: 3.1/stable
          - snap: 2.9/stable
            libjuju: 2.9.42.1
    uses: ./.github/workflows/ci.yaml
    with:
      juju-snap-channel: ${{ matrix.version.snap }}
      libjuju-version-specifier: ${{ matrix.version.libjuju }}

