name: Basic CI workflow caller

on:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  pull_request:

jobs:
  ci-tests-juju-2:
    uses: ./.github/workflows/ci.yaml
    with:
      juju-snap-channel: 2.9/stable
      libjuju-version-specifier: 2.9.42.1

  ci-tests-juju-3:
    uses: ./.github/workflows/ci.yaml
    with:
      juju-snap-channel: 3.1/stable
      libjuju-version-specifier: 3.1.0.1
