# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Pre-integration checks

on:
  workflow_call:
    inputs:
      libjuju-version-specifier:
        description: |
            python-libjuju version specifier (e.g. ">=1.3")
            https://packaging.python.org/en/latest/glossary/#term-Version-Specifier
        required: false
        type: string

jobs:
  lint:
    name: Lint
    uses: canonical/data-platform-workflows/.github/workflows/lint.yaml@v7.0.0

  unit-test:
    name: Unit test charm
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run tests
        run: tox run -e unit
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3

  # lib-check:
  #   name: Check libraries
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Check libs
  #       uses: canonical/charming-actions/check-libraries@2.3.0
  #       with:
  #         credentials: ${{ secrets.CHARMHUB_TOKEN }} # FIXME: current token will expire in 2023-07-04
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         use-labels: false
  #         fail-build: ${{ github.event_name == 'pull_request' }}
