# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to 2/edge

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
    branches:
      - 2/edge

jobs:

  ci-tests:
    name: Tests
    uses: ./.github/workflows/ci.yaml
    permissions:
      contents: write  # Needed for Allure Report

  release:
    name: Release charm | ${{ matrix.path }}
    strategy:
      matrix:
        path:
          - machine
          - kubernetes
    needs:
      - ci-tests
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_edge.yaml@v50.0.0
    with:
      path-to-charm-directory: ${{ matrix.path }}
      track: "2"
      artifact-prefix: ${{ needs.ci-tests.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      contents: write  # Needed to create git tags
      actions: read # Needed by reusable workflow
