# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    uses: canonical/data-platform-workflows/.github/workflows/lint.yaml@v21.0.1
